import Foundation

/// Renders a `ProjectModel` as Markdown.
///
/// The model is the only thing this reads. There is no second pass over the
/// project, so nothing written here can contradict what `inspect` printed from
/// the same facts, and a section with no data is left out rather than filled
/// with a plausible sentence.
///
/// Output is deterministic for a given project and Keel version. There is
/// deliberately no timestamp: a generated file that changes on every run buries
/// the change that mattered in noise, and when a document was written is not a
/// fact about the project anyway.
public struct ProjectDocument {

    /// Identifies a file as Keel's own output, so regenerating can tell it
    /// apart from something a person wrote by hand.
    public static let marker = "<!-- Generated by Keel"

    public let model: ProjectModel
    /// Optional interpretation from an agent the user selected. Absent unless
    /// `--ai` was passed, which is what keeps the document deterministic by
    /// default.
    public let interpretation: Interpretation?

    public init(model: ProjectModel, interpretation: Interpretation? = nil) {
        self.model = model
        self.interpretation = interpretation
    }

    /// Validated fields from an agent, kept separate from everything Keel
    /// derived.
    ///
    /// It carries the agent's name because an unattributed paragraph in a file
    /// full of measured facts reads as another measured fact.
    public struct Interpretation: Sendable, Equatable {
        public let fields: ProjectInterpretation
        public let agentName: String

        public init(fields: ProjectInterpretation, agentName: String) {
            self.fields = fields
            self.agentName = agentName
        }
    }

    /// Fences the one section Keel did not derive, so it can be found, removed
    /// or regenerated without touching anything measured.
    public static let overviewStart = "<!-- keel:overview:start -->"
    public static let overviewEnd = "<!-- keel:overview:end -->"

    /// True when `text` is a document Keel wrote, and is therefore safe to
    /// replace without asking.
    public static func isGenerated(_ text: String) -> Bool {
        text.contains(marker)
    }

    // MARK: - Rendering

    public func markdown() -> String {
        var sections: [String] = [heading()]

        if let interpretation { sections.append(render(interpretation)) }

        sections += [
            atAGlance(),
            architecture(),
            structure(),
            workingOnIt(),
            targets(),
            dependencies(),
            schemes(),
            source(),
        ].compactMap { $0 }

        // Last, and invisible when rendered: what this document was written
        // about, so `--check` can say what changed rather than only that
        // something did.
        sections.append(DocumentFingerprint(model: model).embedded())
        sections.append(footer())

        return sections.joined(separator: "\n\n") + "\n"
    }

    // MARK: Heading

    private func heading() -> String {
        """
        # \(model.name)

        \(Self.marker) \(KeelVersion.current). Re-run `keel document` to update. -->

        \(model.architecture.summary)
        """
    }

    // MARK: Overview

    private func render(_ interpretation: Interpretation) -> String {
        let fields = interpretation.fields
        var parts: [String] = [
            Self.overviewStart,
            "## Overview",
            """
            > [!NOTE]
            > Interpretation from \(interpretation.agentName), based on the facts in \
            this document. Keel checked its shape, not its claims. Every other section \
            is derived by static analysis.
            """,
        ]

        // Keel writes these headings, so the agent cannot open a section that
        // looks like one Keel measured.
        if let overview = fields.overview { parts.append(overview) }
        if let dataFlow = fields.dataFlow {
            parts.append("### Data flow\n\n\(dataFlow)")
        }
        parts += list("Conventions noticed", fields.conventions)
        parts += list("Worth being careful about", fields.risks)
        parts += list("Where to start", fields.onboarding)

        parts.append(Self.overviewEnd)
        return parts.joined(separator: "\n\n")
    }

    private func list(_ heading: String, _ items: [String]) -> [String] {
        guard !items.isEmpty else { return [] }
        return ["### \(heading)\n\n" + items.map { "- \(escaped($0))" }.joined(separator: "\n")]
    }

    // MARK: At a glance

    private func atAGlance() -> String? {
        var rows: [[String]] = []

        if !model.platforms.isEmpty {
            rows.append(["Platform", model.platforms.joined(separator: ", ")])
        }
        if let deployment = model.minimumDeploymentTarget {
            rows.append(["Minimum OS", deployment])
        }
        if let swift = model.swiftVersion {
            rows.append(["Swift", swift])
        }
        if let bundleID = model.appTargets.compactMap(\.bundleIdentifier).first {
            rows.append(["Bundle identifier", "`\(bundleID)`"])
        }
        if let strict = model.allTargets.compactMap(\.strictConcurrency).first {
            rows.append(["Strict concurrency", strict])
        }
        if model.source.swiftFileCount > 0 {
            rows.append(["Swift files", "\(model.source.swiftFileCount)"])
            rows.append(["Lines", "\(model.source.lineCount)"])
        }

        guard !rows.isEmpty else { return nil }
        return "## At a glance\n\n" + table(["", ""], rows)
    }

    // MARK: Architecture

    private func architecture() -> String? {
        let findings = model.architecture.findings
        guard !findings.isEmpty else { return nil }

        let rows = findings.map { finding in
            [
                finding.dimension,
                finding.value,
                finding.support == .undetermined ? "—" : finding.support.displayName,
            ]
        }

        // The basis column is the point: a type marked @Observable is a fact
        // about the code, and a type named ArticleViewModel is a fact about
        // what someone called it.
        var section = """
            ## Architecture

            Inferred from the project's own files. The basis column says whether \
            a finding came from the code itself or from a naming convention; \
            where the evidence settles nothing, the finding says so rather than \
            offering the likeliest answer.

            """
        section += "\n" + table(["Aspect", "Finding", "Basis"], rows)

        let evidence = findings
            .map { finding in
                "**\(finding.dimension) — \(finding.value)**\n\n"
                    + finding.evidence.map { "- \(escaped($0))" }.joined(separator: "\n")
            }
            .joined(separator: "\n\n")

        section += """


        <details>
        <summary>The evidence behind each finding</summary>

        \(evidence)

        </details>
        """

        return section
    }

    // MARK: Working on it

    /// The section written for whoever picks this project up next.
    ///
    /// Every rule describes what the project already does, and every
    /// prohibition is one `keel check` enforces — so following this document
    /// and passing the checker cannot come apart.
    private func workingOnIt() -> String? {
        let context = ProjectContext(model: model)
        var parts: [String] = []

        func bullets(_ heading: String, _ items: [String]) {
            guard !items.isEmpty else { return }
            parts.append("### \(heading)\n\n" + items.map { "- \($0)" }.joined(separator: "\n"))
        }

        bullets("Architecture rules", context.architectureRules())
        bullets("Conventions", context.conventions())
        bullets("Dependencies", context.dependencyRules())
        bullets("Do not", context.prohibitions())

        let files = context.importantFiles()
        if !files.isEmpty {
            parts.append(
                "### Start here\n\n"
                    + table(["Path", "What it is"], files.map { [escaped($0.path), $0.purpose] })
            )
        }

        let commands = context.commands()
        if !commands.isEmpty {
            parts.append(
                "### Commands\n\n"
                    + table(
                        ["Command", "Purpose"],
                        commands.map { ["`\(escaped($0.command))`", $0.purpose] }
                    )
            )
        }

        let concerns = context.concerns()
        if concerns.isEmpty {
            parts.append("### Known concerns\n\nNone. `keel check` reports nothing.")
        } else {
            parts.append(
                "### Known concerns\n\n"
                    + concerns.map { concern in
                        let where_ = concern.location.map { " (\(escaped($0)))" } ?? ""
                        return "- **\(concern.severity.displayName)** \(escaped(concern.message))\(where_)"
                    }.joined(separator: "\n")
            )
        }

        guard !parts.isEmpty else { return nil }
        return "## Working on this project\n\n" + parts.joined(separator: "\n\n")
    }

    // MARK: Structure

    private func structure() -> String? {
        var parts: [String] = []

        if !model.modules.isEmpty {
            parts.append(
                "### Modules\n\n"
                    + table(
                        ["Module", "Swift files"],
                        model.modules.map { [escaped($0.name), "\($0.swiftFileCount)"] }
                    )
            )
        }

        if !model.features.isEmpty {
            parts.append(
                "### Features\n\n"
                    + table(
                        ["Feature", "Layers", "Swift files"],
                        model.features.map { feature in
                            [
                                escaped(feature.name),
                                feature.layers.isEmpty
                                    ? "—"
                                    : feature.layers.map { escaped($0) }.joined(separator: ", "),
                                "\(feature.swiftFileCount)",
                            ]
                        }
                    )
            )
        }

        guard !parts.isEmpty else { return nil }
        return "## Structure\n\n" + parts.joined(separator: "\n\n")
    }

    // MARK: Targets

    private func targets() -> String? {
        let targets = model.allTargets
        guard !targets.isEmpty else { return nil }

        return "## Targets\n\n"
            + table(
                ["Target", "Product", "Minimum OS"],
                targets.map { target in
                    [
                        escaped(target.name),
                        target.productType.displayName,
                        target.deploymentTarget ?? "—",
                    ]
                }
            )
    }

    // MARK: Dependencies

    private func dependencies() -> String? {
        guard !model.dependencies.isEmpty else {
            // An empty list is itself a fact, and a notable one for an iOS
            // project. It is reported, not inferred.
            return "## Dependencies\n\nNo package dependencies."
        }

        return "## Dependencies\n\n"
            + table(
                ["Package", "Requirement"],
                model.dependencies.map { package in
                    [escaped(package.name), package.requirement.map(escaped) ?? "—"]
                }
            )
    }

    // MARK: Schemes

    private func schemes() -> String? {
        guard !model.schemes.isEmpty else { return nil }

        var section = "## Schemes\n\n"
            + model.schemes
                .map { "- \(escaped($0.name))\($0.isShared ? "" : " — not shared")" }
                .joined(separator: "\n")

        // A scheme under xcuserdata is gitignored: CI cannot build it, and
        // neither can a colleague on a fresh clone.
        let unshared = model.schemes.filter { !$0.isShared }
        if !unshared.isEmpty {
            section += """


            > [!WARNING]
            > \(unshared.count == 1 ? "One scheme is" : "\(unshared.count) schemes are") not shared, \
            so a fresh clone and CI cannot build \(unshared.count == 1 ? "it" : "them").
            """
        }

        return section
    }

    // MARK: Source

    private func source() -> String? {
        guard model.source.swiftFileCount > 0 else { return nil }

        var parts: [String] = []

        let declarations = model.analysis.declarationCounts()
        if !declarations.isEmpty {
            var rows = declarations.map { [$0.kind.displayName, "\($0.count)"] }
            rows.append(["function", "\(model.analysis.functionCount)"])
            if model.analysis.asyncFunctionCount > 0 {
                rows.append(["async function", "\(model.analysis.asyncFunctionCount)"])
            }
            if model.analysis.throwingFunctionCount > 0 {
                rows.append(["throwing function", "\(model.analysis.throwingFunctionCount)"])
            }
            parts.append("### Declarations\n\n" + table(["Kind", "Count"], rows))
        }

        let patterns = model.analysis.notablePatterns()
        if !patterns.isEmpty {
            parts.append(
                "### Patterns\n\n"
                    + table(["Pattern", "Types"], patterns.map { [$0.name, "\($0.count)"] })
            )
        }

        let imports = model.analysis.importCounts().prefix(10)
        if !imports.isEmpty {
            parts.append(
                "### Most imported\n\n"
                    + table(
                        ["Module", "Files"],
                        imports.map { [escaped($0.module), "\($0.files)"] }
                    )
            )
        }

        parts.append(testing())

        return "## Source\n\n" + parts.joined(separator: "\n\n")
    }

    private func testing() -> String {
        var frameworks: [String] = []
        if model.source.usesSwiftTesting { frameworks.append("Swift Testing") }
        if model.source.usesXCTest { frameworks.append("XCTest") }

        guard !model.testTargets.isEmpty || !frameworks.isEmpty else {
            return """
                ### Testing

                > [!WARNING]
                > No test target and no testing framework found.
                """
        }

        var lines: [String] = []
        if !model.testTargets.isEmpty {
            lines.append("- Test targets: \(model.testTargets.map { escaped($0.name) }.joined(separator: ", "))")
        }
        if !frameworks.isEmpty {
            lines.append("- Frameworks: \(frameworks.joined(separator: ", "))")
        }

        return "### Testing\n\n" + lines.joined(separator: "\n")
    }

    // MARK: Footer

    private func footer() -> String {
        """
        ---

        <sub>Written by [Keel](https://github.com/GRimAce11/Keel) \(KeelVersion.current) from \
        static analysis of this project — no build, no network, no AI. Anything Keel could not \
        determine is absent rather than guessed.</sub>
        """
    }

    // MARK: - Markdown helpers

    private func table(_ headers: [String], _ rows: [[String]]) -> String {
        var lines = [
            "| " + headers.joined(separator: " | ") + " |",
            "|" + headers.map { _ in "---" }.joined(separator: "|") + "|",
        ]
        lines += rows.map { "| " + $0.joined(separator: " | ") + " |" }
        return lines.joined(separator: "\n")
    }

    /// A pipe in a value would end the table cell it sits in.
    private func escaped(_ text: String) -> String {
        text.replacingOccurrences(of: "|", with: "\\|")
    }
}
